import { useEffect } from 'react';
import { Linking, AppState } from 'react-native';
import { useActivityMode, ActivityMode } from '../context/ActivityModeContext';

// 2026-04-27 (cold-start race fix): module-scoped ref holding the most
// recent unhandled initial URL. If iOS suspends the app before the
// `getInitialURL()` promise resolves, the URL would otherwise be lost
// on resume. The AppState listener inside `useDeepLinks` re-fires
// `handleDeepLink` with this URL when the app comes back to active.
// Cleared after a successful navigation to prevent repeat firings.
let pendingInitialURL: string | null = null;

/**
 * Deep Link Router
 *
 * Parses and routes mdhuntfish:// (custom scheme) and https://mdhuntfishoutdoors.com/i/{code}
 * (universal link) URLs to the correct screen and params.
 *
 * Supported routes:
 *   - mdhuntfish://camp/invite/{code}          → Hunt mode → DeerCampTab + inviteCode
 *   - https://mdhuntfishoutdoors.com/i/{code}  → Hunt mode → DeerCampTab + inviteCode
 *
 * V2.2.0 notes:
 *   - The prior version referenced CampInviteScreen / HikeScreen / HuntScreen screens
 *     that were never implemented. Those routes have been removed so the router no
 *     longer navigates to non-existent targets. Only the camp-invite flow is wired.
 *
 * 2026-04-20 fix:
 *   - Previous implementation routed camp invites to `GroupCampTab` under Camp mode.
 *     That screen is the standalone Camp-mode group trip surface, NOT the Deer Camp
 *     shared-map social surface. After the Deer Camp area-redesign, invite codes
 *     belong to the Hunt-mode `DeerCampTab` (parent `HuntTabs`), so the router now
 *     targets that tab and switches ActivityMode to 'hunt' first.
 */

/**
 * Represents a parsed deep link result.
 *
 * mode (optional): if set, the app should switch to this ActivityMode before
 * navigating so the target tab exists in the current tab navigator.
 *
 * parent (optional): the root-Stack route that owns `screen`. Post-2026-04-20
 * revert, each mode has its own Tab.Navigator hanging off the root Stack
 * (ModePicker → HuntTabs | FishTabs | CampTabs | HikeTabs), so nested-screen
 * navigation needs `{ screen, params }` addressed to the parent route.
 */
export interface DeepLinkRoute {
  screen: string;
  params: Record<string, string>;
  mode?: ActivityMode;
  parent?: 'HuntTabs' | 'FishTabs' | 'CampTabs' | 'HikeTabs';
}

/** Tab name inside HuntTabs that owns the Deer Camp social surface. */
const DEER_CAMP_TAB = 'DeerCampTab';

/**
 * Tab name inside CampTabs that owns the Camp Trip Planner / saved
 * trips list. 2026-04-30 (V2.4 step 1): added so trip-invite Universal
 * Links land on the planner where the joinByInviteCode UI lives.
 *
 * Trip invite URL: /huntmaryland-site/trip/{code}.
 */
const CAMP_TRIP_PLANNER_TAB = 'CampTripPlannerTab';

/**
 * Parse a deep link URL into a screen name and params.
 *
 * @param url - The URL to parse
 * @returns Route object with screen and params, or null if unrecognized
 *
 * Examples:
 *   parseLink('mdhuntfish://camp/invite/abc123')
 *     → { screen: 'DeerCampTab', params: { inviteCode: 'abc123' }, mode: 'hunt', parent: 'HuntTabs' }
 *   parseLink('https://mdhuntfishoutdoors.com/i/abc123')
 *     → { screen: 'DeerCampTab', params: { inviteCode: 'abc123' }, mode: 'hunt', parent: 'HuntTabs' }
 */
export function parseLink(url: string): DeepLinkRoute | null {
  if (!url) return null;

  try {
    // Custom scheme: mdhuntfish://...
    if (url.startsWith('mdhuntfish://')) {
      const path = url.replace('mdhuntfish://', '');
      const parts = path.split('/').filter(Boolean);

      if (parts.length >= 2) {
        const [resource, action, ...rest] = parts;
        const id = rest.join('/'); // Handle multi-segment IDs

        // mdhuntfish://camp/invite/{code}
        if (resource === 'camp' && action === 'invite' && id) {
          return {
            screen: DEER_CAMP_TAB,
            params: { inviteCode: id },
            mode: 'hunt',
            parent: 'HuntTabs',
          };
        }
      }

      return null;
    }

    // 2026-04-28 (audit-of-audit): the `mdhuntfishoutdoors.com/i/{code}`
    // branch was removed here. We never owned that domain, so iOS would
    // never route those URLs to our app via AASA in the first place — the
    // branch was dead code. Removing it is defense-in-depth: if the
    // domain is ever registered by someone else, that party cannot
    // accidentally open our deer-camp join flow because we no longer
    // claim that pattern. Originally added before fork consolidation
    // when the domain was tentatively registered; that registration
    // never completed.

    // 2026-04-27 (App Store prep): legacy share-link format generated by
    // deepLinkService (still in use because GitHub Pages hosts the AASA at
    // davidstonko.github.io/huntmaryland-site/.well-known/apple-app-site-association).
    // Recipients of "Share Link via Messages" invites land here; without
    // this branch, deepLinkRouter dropped the URL silently and the app
    // ignored the invite. Format: /huntmaryland-site/join/{code}.
    if (
      url.startsWith('https://davidstonko.github.io/huntmaryland-site/') ||
      url.startsWith('http://davidstonko.github.io/huntmaryland-site/')
    ) {
      // 2026-04-30 (V2.4 step 1): Camp Trip invite URLs land here
      // first, then fall through to the Deer Camp join URL pattern.
      // Format: /huntmaryland-site/trip/{code}. Matched before the
      // join branch because /trip/{code} is more specific.
      const tripMatch = url.match(/\/huntmaryland-site\/trip\/([a-zA-Z0-9]+)/);
      if (tripMatch && tripMatch[1]) {
        return {
          screen: CAMP_TRIP_PLANNER_TAB,
          params: { inviteCode: tripMatch[1] },
          mode: 'camp',
          parent: 'CampTabs',
        };
      }
      const m = url.match(/\/huntmaryland-site\/join\/([a-zA-Z0-9]+)/);
      if (m && m[1]) {
        return {
          screen: DEER_CAMP_TAB,
          params: { inviteCode: m[1] },
          mode: 'hunt',
          parent: 'HuntTabs',
        };
      }
      return null;
    }

    return null;
  } catch (err) {
    // eslint-disable-next-line no-console
    console.warn('[DeepLinkRouter] Parse error:', err);
    return null;
  }
}

/**
 * Hook to set up deep link listener and navigation.
 * Call this inside your NavigationContainer scope AND inside the
 * ActivityModeProvider scope so it can switch modes before navigating.
 *
 * Usage in App.tsx inside NavigationContainer + ActivityModeProvider:
 *   <DeepLinkInitializer navigationRef={navigationRef} />
 *
 * @param navigationRef - Navigation ref passed from App
 */
export function useDeepLinks(
  navigationRef: React.RefObject<any>,
): void {
  const { activeMode, setActiveMode } = useActivityMode();

  useEffect(() => {
    // Listen for incoming links (app already running)
    const subscription = Linking.addEventListener('url', handleDeepLink);

    // 2026-04-27 (cold-start race fix): cache the initial URL in a
    // module-scoped ref so the AppState resume path can re-trigger
    // handling if the user backgrounded before getInitialURL resolved.
    Linking.getInitialURL()
      .then((url) => {
        if (url != null) {
          pendingInitialURL = url;
          handleDeepLink({ url });
        }
      })
      .catch((err) => {
        // eslint-disable-next-line no-console
        console.warn('[DeepLinkRouter] getInitialURL error:', err);
      });

    // 2026-04-27: AppState resume listener — if iOS suspended us before
    // the initial-URL promise resolved AND that initial URL was a deep
    // link, retry the navigation when we come back to foreground. The
    // module-scoped pendingInitialURL is cleared after a successful
    // navigation so this doesn't fire repeatedly on subsequent resumes.
    const appStateSub = AppState.addEventListener('change', (nextState) => {
      if (nextState === 'active' && pendingInitialURL) {
        const url = pendingInitialURL;
        // Don't clear yet — handleDeepLink will navigate, then we clear.
        handleDeepLink({ url });
      }
    });

    return () => {
      subscription.remove();
      appStateSub.remove();
    };

    function handleDeepLink(event: { url: string }): void {
      const route = parseLink(event.url);
      if (!route || !navigationRef.current) return;

      // If the route targets a tab that only exists in a different mode,
      // switch modes first. The tab navigator re-renders and the target tab
      // becomes reachable.
      if (route.mode && route.mode !== activeMode) {
        setActiveMode(route.mode);
      }

      // Navigate on the next tick so the tab navigator has mounted the
      // destination mode's tabs before we try to navigate into them.
      setTimeout(() => {
        if (!navigationRef.current) return;
        if (route.parent) {
          // Nested navigation: address the root-Stack parent route and pass
          // the tab name + params via the { screen, params } shape.
          navigationRef.current.navigate(route.parent, {
            screen: route.screen,
            params: route.params,
          });
        } else {
          navigationRef.current.navigate(route.screen, route.params);
        }
        // 2026-04-27: clear the pending initial URL ref so the AppState
        // resume path doesn't re-fire on subsequent foreground events.
        if (pendingInitialURL === event.url) {
          pendingInitialURL = null;
        }
      }, 50);
    }
  }, [navigationRef, activeMode, setActiveMode]);
}
